version: "3.9"
services:
  web:
    image: marcpartensky/ialab:latest
    build:
      target: web
    # volumes:
    #   - ./data:/root/data

  train:
    image: marcpartensky/ialab:train
    volumes:
      - ./data:/root/data
    environment:
      CHECKPOINTS: false
    build:
      target: training
