version: "3.9"

services:
  ialab:
    image: marcpartensky/ialab
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: server.py
    ports:
      - "8000:8000"
