version: "3.9"
services:
  ialab:
    image: marcpartensky/ialab
    build:
      target: web
    volumes:
      - ./data:/root/data

  train:
    image: marcpartensky/ialab
    volumes:
      - ./data:/root/data
    build:
      target: training
